-- Replace the specific seeded itinerary wording with general wording.
-- Every update is guarded: a field is only changed while it still equals the original seeded text,
-- so anything edited in admin is left alone. Running it twice changes nothing.

UPDATE "ChardhamPackage" SET "startPoint" = $g$Dehradun$g$
  WHERE "slug" = 'char-dham' AND "startPoint" = $g$Sahastradhara Helipad, Dehradun$g$;
UPDATE "ChardhamPackage" SET "howItStarts" = $g$Your yatra begins in Dehradun, the gateway to the Garhwal Himalayas. Our team meets you on arrival, explains the plan, the helicopter guidelines and the weather outlook, and confirms your departure details. The flights begin from the helipad our team confirms for your date.$g$
  WHERE "slug" = 'char-dham' AND "howItStarts" = $g$Your yatra begins in Dehradun, the gateway to the Garhwal Himalayas. Our team meets you on arrival, takes you to your hotel and, in the evening, explains the route, the helicopter rules and the weather outlook. The flights begin the next morning from Sahastradhara Helipad.$g$;
UPDATE "ChardhamPackage" SET "importantInfo" = $g$Flights, darshan and transfers depend on the weather, airspace rules and permissions from the local authorities.
Keep two to three spare days in your plan in case bad weather delays the flights.
Darshan at each dham is the main part of the yatra. Extra sightseeing depends on time and weather.
Porter, pony and palki services are paid for locally and are not part of the package.
Carry warm clothes; the dhams are at high altitude and it can be cold.$g$
  WHERE "slug" = 'char-dham' AND "importantInfo" = $g$Flights, darshan and transfers depend on the weather, airspace rules and permissions from the local authorities.
Keep two to three spare days in your plan in case bad weather delays the flights.
Darshan at each dham is the main part of the yatra. Extra sightseeing depends on time and weather.
Porter, pony and palki services are paid for locally and are not part of the package.
Carry warm clothes; Kedarnath is at an altitude of about 11,500 feet.$g$;
UPDATE "ChardhamPackage" SET "inclusions" = ARRAY[$g$Helicopter flights between the dhams, as per the plan$g$, $g$Stay during the yatra$g$, $g$Meals as per the plan$g$, $g$Pick-up and drop at your arrival and departure point in Dehradun$g$, $g$A briefing before the yatra begins$g$, $g$Assistance and guidance at every dham$g$]::text[]
  WHERE "slug" = 'char-dham' AND "inclusions" = ARRAY[$g$Helicopter flights between the dhams, as per the plan$g$, $g$Hotel stays during the yatra$g$, $g$Meals as per the plan$g$, $g$Pick-up and drop at Dehradun airport or railway station$g$, $g$A briefing before the yatra begins$g$, $g$Assistance and guidance at every dham$g$]::text[];
UPDATE "ChardhamPackage" SET "steps" = $g$[{"title": "Arrive in Dehradun", "description": "Our team receives you on arrival and takes you to your stay. Rest and attend a short briefing about the plan for the coming days.", "featured": false}, {"title": "Yamunotri", "imageUrl": "/seed-images/dham-yamunotri.jpg", "description": "Fly to the helipad nearest to Yamunotri, then continue to the temple by road and a short trek, with a pony or palki available if you need one. Have darshan at the shrine where the Yamuna River begins, then return for your stay.", "featured": true}, {"title": "Gangotri", "imageUrl": "/seed-images/dham-gangotri.jpg", "description": "Fly towards Gangotri and travel the last stretch by road, alongside the river and through mountain villages. Have darshan at the temple where the Ganga is worshipped at her place of origin, then return for your stay.", "featured": true}, {"title": "Kedarnath", "imageUrl": "/seed-images/dham-kedarnath.jpg", "description": "Fly to the Kedarnath helipad, usually in short connecting flights. Flight slots are set by the aviation authorities. A walk from the helipad leads to the temple of Lord Shiva; porters and ponies are available locally for an extra charge.", "featured": true}, {"title": "Badrinath", "imageUrl": "/seed-images/dham-badrinath.jpg", "description": "Fly to Badrinath, weather permitting. The temple of Lord Vishnu is a short drive and walk from the helipad. If time allows, visit the sacred sites nearby.", "featured": true}, {"title": "Return to Dehradun", "description": "Fly back to Dehradun and move on to your departure point, where the yatra ends.", "featured": false}]$g$::jsonb
  WHERE "slug" = 'char-dham' AND "steps" = $g$[{"title": "Arrive in Dehradun", "description": "A driver meets you at Jolly Grant Airport or the railway station and takes you to your hotel. Rest, enjoy dinner and attend the briefing about the plan for the coming days.", "featured": false}, {"title": "Yamunotri", "imageUrl": "/seed-images/dham-yamunotri.jpg", "description": "Fly from Sahastradhara Helipad in Dehradun to Kharsali (about 30 to 35 minutes). A short ride takes you to Jankichatti, where a 6.5 km walk, pony or palki ride leads to the Yamunotri Temple, the source of the Yamuna River, at about 10,800 feet. After darshan, return to Kharsali for the night.", "featured": true}, {"title": "Gangotri", "imageUrl": "/seed-images/dham-gangotri.jpg", "description": "Fly from Kharsali to Jhala Helipad, then drive about 25 km to the Gangotri Temple at about 10,200 feet, where the Ganga is worshipped at her place of origin. The road passes the Bhagirathi River and small mountain villages. After darshan, return to Jhala and on to your hotel.", "featured": true}, {"title": "Kedarnath", "imageUrl": "/seed-images/dham-kedarnath.jpg", "description": "Fly to Phata, then take a short shuttle flight to Kedarnath Helipad. The shuttle runs in time slots allotted by UCADA, the Uttarakhand Civil Aviation Development Authority. From the helipad it is a walk of about 700 metres to the temple, which stands at about 11,755 feet. Porters and ponies are available on site for an extra charge.", "featured": true}, {"title": "Badrinath", "imageUrl": "/seed-images/dham-badrinath.jpg", "description": "Fly from Phata to Badrinath (about 30 minutes, weather permitting). The temple is about 1 km from the helipad; a short drive and a walk of 150 to 200 metres bring you to the entrance, followed by about 25 stone steps. Nearby you can bathe at Tapt Kund and visit Mana village if time allows.", "featured": true}, {"title": "Return to Dehradun", "description": "A helicopter flight of about one hour brings you back to Dehradun, and you are then taken to the airport or railway station, where the yatra ends.", "featured": false}]$g$::jsonb;

UPDATE "ChardhamPackage" SET "startPoint" = $g$Dehradun$g$
  WHERE "slug" = 'any-dham' AND "startPoint" = $g$Sahastradhara Helipad, Dehradun$g$;
UPDATE "ChardhamPackage" SET "howItStarts" = $g$Send us a request with the dham or dhams you want to visit and your preferred date. Our team confirms availability, the flight plan and the price, and guides you on your arrival in Dehradun, where the yatra begins.$g$
  WHERE "slug" = 'any-dham' AND "howItStarts" = $g$Send us a request with the dham or dhams you want to visit and your preferred date. Our team confirms availability, the flight plan and the price, and then helps you with your arrival in Dehradun, where the yatra begins.$g$;
UPDATE "ChardhamPackage" SET "importantInfo" = $g$Flights, darshan and transfers depend on the weather, airspace rules and permissions from the local authorities.
Keep two to three spare days in your plan in case bad weather delays the flights.
Some dhams can often be combined in a single day when the weather and the flight slots allow.
Porter, pony and palki services are paid for locally and are not part of the package.$g$
  WHERE "slug" = 'any-dham' AND "importantInfo" = $g$Flights, darshan and transfers depend on the weather, airspace rules and permissions from the local authorities.
Keep two to three spare days in your plan in case bad weather delays the flights.
Kedarnath and Badrinath can often be visited together in a single day from Dehradun when the weather and the shuttle slots allow.
Porter, pony and palki services are paid for locally and are not part of the package.$g$;

UPDATE "ChardhamPackage" SET "startPoint" = $g$The helipad where your helicopter lands$g$
  WHERE "slug" = 'yamunotri-gangotri-handling' AND "startPoint" = $g$Kharsali Helipad (Yamunotri) and Jhala or Harsil Helipad (Gangotri)$g$;
UPDATE "ChardhamPackage" SET "steps" = $g$[{"title": "Share your flight details", "description": "Send us your dates, the number of pilgrims and the helipad where you will land, so that our team can plan the ground arrangements.", "featured": false}, {"title": "Welcome at the helipad", "description": "Our representative receives you at the helipad and explains the plan for the visit.", "featured": false}, {"title": "Yamunotri", "description": "From the helipad, we guide you on to the temple by road and a short trek. We help arrange a pony, a palki or a porter if you need one (paid locally), and guide you through darshan at the temple of Goddess Yamuna.", "featured": false}, {"title": "Gangotri", "description": "From the helipad, a road journey leads to the Gangotri Temple. We arrange the transfer and guide you through darshan at the place where the Ganga is worshipped at her source.", "featured": false}, {"title": "Return to your helicopter", "description": "After darshan, we take you back to the helipad in time for your return flight and stay with you until you leave.", "featured": false}]$g$::jsonb
  WHERE "slug" = 'yamunotri-gangotri-handling' AND "steps" = $g$[{"title": "Share your flight details", "description": "Send us your dates, the number of pilgrims and the helipad where you will land, so that our team can plan the ground arrangements.", "featured": false}, {"title": "Welcome at the helipad", "description": "Our representative receives you at Kharsali for Yamunotri, or at Jhala or Harsil for Gangotri, and explains the plan for the visit.", "featured": false}, {"title": "Yamunotri", "description": "From Kharsali, a short ride takes you to Jankichatti, where the 6.5 km walk to the temple begins. We help you arrange a pony, a palki or a porter if you need one (paid locally), and guide you through darshan at the temple of Goddess Yamuna.", "featured": false}, {"title": "Gangotri", "description": "From the helipad, a road journey of about 25 km leads to the Gangotri Temple. We arrange the transfer and guide you through darshan at the place where the Ganga is worshipped at her source.", "featured": false}, {"title": "Return to your helicopter", "description": "After darshan, we take you back to the helipad in time for your return flight and stay with you until you leave.", "featured": false}]$g$::jsonb;
